### ISSUE TITLE
Korean Scrap doesn't work

### ISSUE THREAD

**Issue by HarshitChari** [kaycmendes/opgg-scraper#1]
if(region === 'kr'){
 await page.goto(`https://$www.op.gg/summoner/userName=${user}`)
}else{
 await page.goto(`https://${region}.op.gg/summoner/userName=${user}`)
}

**Comment by kaycmendes** [comment]
Yeah, I think it should be op.gg only cause it goes to Korea by default

**Comment by HarshitChari** [comment]
I have created a pull request and added a necessary change! you can merge to fix it

**Comment by kaycmendes** [comment]
Merged it
