### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by johntaxmi** [kaycmendes/opgg-scraper#3]
Am getting **Error: No node found for selector: #right_gametype_soloranked** while running the command.
And if i change the refresh to true then am getting **Error: No node found for selector: #SummonerRefreshButton**

**Comment by kaycmendes** [comment]
Opgg probably changed the element id of this specific element, I'll fix it tomorrow

**Comment by kaycmendes** [comment]
They had all classes re-named, everything is working now.
